name: Deploy to ec2

on:
    push:
      branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: ssh deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo su
          cd /var/www/html/hotel-miranda-laravel
          git pull
          composer install
          php artisan migrate:fresh --seed --force
          php artisan cache:clear
          systemctl restart apache2
